###################################################################
##################### SERVICE CONFIGURATION #######################
###################################################################

service:
    #Service will start listening on this port
    port: 8088
    #If tables for the scheduler do not exist in the DB, create 
    #them.
    createTablesIfNotExists: true

#####################   DB CONFIGURATION    #######################
database:
  driverClass: com.mysql.jdbc.Driver
  user: <db_user>     
  password: <db_pwd>
  url: jdbc:mysql://localhost:3306/cassata
  initialSize: 5
  minSize: 2
  maxSize: 20
  properties:
    acquireIncrement: 5
    numHelperThreads: 3
    checkoutTimeout: 10000

#####################  LOGGING CONFIGURATION #######################
logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ../logs/service.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ../logs/service-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: 

##################### DROP WIZARD CONFIGURATION ####################
server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ../logs/service-requests.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: ../logs/service-requests%d.log
        archivedFileCount: 5
        timeZone: UTC
        logFormat: 
