service:
    port: 8088
    createTablesIfNotExists: true

database:
  driverClass: com.mysql.jdbc.Driver
  user: rw
  password: password123
  url: jdbc:mysql://localhost:3306/cassata
  initialSize: 5
  minSize: 2
  maxSize: 20
  properties:
    acquireIncrement: 5
    numHelperThreads: 3
    checkoutTimeout: 10000

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: ../logs/service.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ../logs/service-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: 

server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ../logs/service-requests.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: ../logs/service-requests%d.log
        archivedFileCount: 5
        timeZone: UTC
        logFormat: 
